-- AlterTable
ALTER TABLE "Company" ALTER COLUMN "companyName" SET DATA TYPE VARCHAR(200);
ALTER TABLE "Company" ALTER COLUMN "website" SET DATA TYPE VARCHAR(2048);
ALTER TABLE "Company" ALTER COLUMN "industry" SET DATA TYPE VARCHAR(200);
